name: Azure VM Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure target directory exists on Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }} # moc
          username: ${{ secrets.AZURE_VM_USER }} # moc
          key: ${{ secrets.AZURE_VM_KEY }} # moc，私钥内容
          port: ${{ secrets.AZURE_VM_PORT }} # moc, 默认22
          script: |
            sudo -i mkdir -p /home/Bingo_HR
            sudo -i chown bingo:bingo /home/Bingo_HR

      - name: Generate systemd service file
        run: |
          echo '[Unit]' > bingo-flask.service
          echo 'Description=Bingo HR Flask Service' >> bingo-flask.service
          echo 'After=network.target' >> bingo-flask.service
          echo '' >> bingo-flask.service
          echo '[Service]' >> bingo-flask.service
          echo 'User=bingo' >> bingo-flask.service
          echo 'Group=bingo' >> bingo-flask.service
          echo 'WorkingDirectory=/home/Bingo_HR' >> bingo-flask.service
          echo 'Environment="PATH=/home/Bingo_HR/.venv/bin"' >> bingo-flask.service
          echo 'ExecStart=/home/Bingo_HR/.venv/bin/python /home/Bingo_HR/app.py' >> bingo-flask.service
          echo 'Restart=always' >> bingo-flask.service
          echo 'RestartSec=3' >> bingo-flask.service
          echo '' >> bingo-flask.service
          echo '[Install]' >> bingo-flask.service
          echo 'WantedBy=multi-user.target' >> bingo-flask.service

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }} # moc
          username: ${{ secrets.AZURE_VM_USER }} # moc
          key: ${{ secrets.AZURE_VM_KEY }} # moc，私钥内容
          port: ${{ secrets.AZURE_VM_PORT }} # moc, 默认22
          source: '. bingo-flask.service'
          target: '/home/Bingo_HR' # 可根据实际情况调整

      - name: SSH to Azure VM and restart Flask app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }} # moc
          username: ${{ secrets.AZURE_VM_USER }} # moc
          key: ${{ secrets.AZURE_VM_KEY }} # moc，私钥内容
          port: ${{ secrets.AZURE_VM_PORT }} # moc, 默认22
          script: |
            sudo apt-get update && sudo apt-get install -y python3-venv
            sudo -i bash -c "cd /home/Bingo_HR && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"
            sudo mv /home/Bingo_HR/bingo-flask.service /etc/systemd/system/bingo-flask.service
            sudo systemctl daemon-reload
            sudo systemctl enable bingo-flask
            sudo systemctl restart bingo-flask
            sudo systemctl status bingo-flask --no-pager
            sudo -i cat /home/Bingo_HR/app.log || true 